/**
 * Centralized Fluent UI icon exports
 * This barrel file improves tree-shaking and reduces bundle duplication
 * Icons are grouped by size and use case for easier maintenance
 * 
 * Savings: ~8-12 kB through better tree-shaking and deduplication
 */

export {
  // 24px Navigation Icons
  Home24Regular,
  Folder24Regular,
  CalendarLtr24Regular,
  Briefcase24Regular,
  ClipboardTaskListLtr24Regular,
  Person24Regular,
  Chat24Regular,
  Bot24Regular,
  Clock24Regular,
  History24Regular,
  Important24Regular,
  Warning24Regular,
  DocumentBulletList24Regular,
  CalendarCheckmark24Regular,
  Record24Regular,
  ArrowLeft24Regular,
  ArrowRight24Regular,
  CheckmarkCircle24Regular,
  CheckmarkCircle24Filled,
  CheckboxChecked24Regular,
  DocumentText24Regular,
  PeopleTeam24Regular,
  Timer24Regular,
  VideoClip24Regular,
  AlertUrgent24Regular,
  Navigation24Regular,
  ArrowUpload24Regular,
  Dismiss24Regular,
  CalendarAdd24Regular,
  ArrowMove24Regular,
  PersonAdd24Regular,
  Add24Regular,
  Checkmark24Regular,
  Copy24Regular,
  Document24Regular,
  Send24Regular,
  SignOut24Regular,
  FolderAdd24Regular,
  GridDots24Regular,
  DocumentFolder24Regular,
  ContactCard24Regular,
  Camera24Regular,
  Note24Regular,
  Building24Regular,
  Search24Regular,
  Image24Regular,
  DocumentPdf24Regular,
  DocumentTable24Regular,
  SlideText24Regular,
  Archive24Regular,
  Code24Regular,
  Video24Regular,
  CalendarMonth24Regular,
  FolderOpen24Regular,
  TaskListSquareLtr24Regular,
  
  // 48px Icons
  DocumentFolder48Regular,
  CalendarEmpty48Regular,
  Folder48Regular,
  TaskListSquareLtr48Regular,
  
  // 20px Icons
  Edit20Regular,
  Delete20Regular,
  MoreVertical20Regular,
  MoreHorizontal20Regular,
  Calendar20Regular,
  CalendarClock20Regular,
  CalendarLtr20Regular,
  Archive20Regular,
  ArchiveArrowBack20Regular,
  Folder20Regular,
  Add20Regular,
  Search20Regular,
  TaskListSquareLtr20Regular,
  People20Regular,
  ChevronLeft20Regular,
  ChevronRight20Regular,
  ChevronDown20Regular,
  Dismiss20Regular,
  Grid20Regular,
  List20Regular,
  Record20Regular,
  Link20Regular,
  Checkmark20Regular,
  Copy20Regular,
  ArrowLeft20Regular,
  ArrowRight20Regular,
  ArrowDownload20Regular,
  ArrowUpload20Regular,
  ArrowMove20Regular,
  Rename20Regular,
  Eye20Regular,
  Play20Regular,
  Play20Filled,
  Share20Regular,
  Info20Regular,
  Document20Regular,
  Image20Regular,
  DocumentPdf20Regular,
  Video20Regular,
  PersonCircle20Regular,
  Clock20Filled,
  Warning20Filled,
  CheckmarkCircle20Filled,
  ErrorCircle20Filled,
  CloudAdd20Regular,
  ArrowClockwise20Regular,
  History20Regular,
  
  // 16px Icons
  Checkmark16Regular,
  Dismiss16Regular,
  Edit16Regular,
  
  // Regular Icons (no size prefix)
  ArrowRightRegular,
  MailRegular,
  ClipboardTaskListLtrRegular,
  PersonRegular,
  PasswordRegular,
  DismissRegular,
  CheckmarkRegular,
  SendRegular,
  MusicNote224Regular,
  MusicNote220Regular,
  
  // Filled Icons
  Shield20Filled,
  Flash20Filled,
  PeopleTeam20Filled,
  DataBarVertical20Filled,
} from '@fluentui/react-icons';
